### ISSUE TITLE
App status: Synthesizing co-design session

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/team-titan#1080]
We're reviewing and synthesizing what was done in the App status/notifications co-design session and delivering a presentation.

* [x] Theming post-its
* [x] Creating 3 themed solutions
* [ ] Creating draft designs for 3 solutions
* [x] Making recommendations
* [x] Updating draft deck
* [x] Crafting final presentation

**Comment by humancompanion** [comment]
Target date: 9/7

**Comment by humancompanion** [comment]
New target is to meet with Dianna, Alesia, and Michelle late next week. I need to reach out to SaraK to schedule the meeting.

**Comment by timtimtimtimofficial** [comment]
Uploaded latest slide deck to the Google Drive:

usajobs > analysis > notifications > Notifications Outcomes 2018-09-27.pptx

**Missing info from Slide 27:** @mchung07 @humancompanion Can we find quotes / record speaking to HR specialists' pattern of avoiding sending notifications for fear of increased call volume from applicants? 

I found quotes on Min's graphic ("why notifications aren't being sent.pdf" in the same Google Drive folder) that are in the ballpark, but they speak more to workload and technical hinderances rather than a _fear_ of receiving calls from applicants.

**Comment by humancompanion** [comment]
Need to schedule another meeting with OPM leadership.

**Comment by humancompanion** [comment]
Communicate the decisions made at Excella.
